# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76eadaf12e990054d3162844bb357200"
application_url = "https://bench-ratings-paths-dreams.trycloudflare.com"
embedded = true
name = "ShopiGPT"
handle = "shopigpt-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bench-ratings-paths-dreams.trycloudflare.com/auth/callback",
  "https://bench-ratings-paths-dreams.trycloudflare.com/auth/shopify/callback",
  "https://bench-ratings-paths-dreams.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-store-ilker.myshopify.com"
automatically_update_urls_on_dev = true
